spring:
  datasource:
    url: jdbc:mysql://db:3306/computer_guide
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  server:
    port: 8080
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming: # ????? ?? ?????, ????? ? ???????? ??????? ???? ????? ???????? ????????
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.migrations-master.yaml